// Generated by CoffeeScript 1.6.2
var assert, common;

assert = require("pretty-assert");

common = require("../common");

describe('Common', function() {
  return describe('.timesOfDay()', function() {
    it('should have 25 options', function() {
      return assert.equal(25, common.timesOfDay.length);
    });
    return it('should contain only valid values', function() {
      var o, _i, _len, _ref, _results;

      _ref = common.timesOfDay;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        o = _ref[_i];
        assert.finite(o.value);
        _results.push(assert.string(o.text));
      }
      return _results;
    });
  });
});
