// Generated by CoffeeScript 1.6.2
var assert, ectConfig;

assert = require("pretty-assert");

ectConfig = require("../ectConfig");

describe('ectConfig', function() {
  return describe('.timezones', function() {
    return it('should contain only valid values', function(done) {
      ectConfig.timezones(function(timezones) {
        debugger;
        var o, _i, _len;

        for (_i = 0, _len = timezones.length; _i < _len; _i++) {
          o = timezones[_i];
          assert.defined(o.id);
        }
        return done();
      });
      return console.log("hi");
    });
  });
});
