// Generated by CoffeeScript 1.6.2
debugger;
var check, common, ctrl, model, sanitize;

check = require('validator').check;

common = require('../common');

model = require('../database/model');

ctrl = require('ctrl');

sanitize = require('validator').sanitize;

exports.account = function(req, res, data) {
  var user;

  user = req.user.getUser();
  common.logger.debug(user);
  common.logger.debug("exports.account before getCommunication");
  return model.getCommunication(user, function(err, result) {
    var all, result_present;

    common.logger.debug("exports.account getCommunication returned");
    common.logger.debug(user != null ? user.email : void 0);
    if (err) {
      common.logger.error(err);
    }
    all = common._.pluck(result, 'server_received');
    result_present = common._.compact(all);
    return res.render('account.ect', common.extend({
      page: 'Account',
      req: req,
      user: {
        messagesReceived: result_present.length,
        messagesSent: all.length - result_present.length,
        timezone: user.timezone_id,
        name: user.name,
        credits: user.credit,
        email: user.email,
        lowerTimeEstimate: user.credit / 10,
        upperTimeEstimate: user.credit / 5
      },
      warningLevel: function(daysLeft) {
        if (daysLeft < 1) {
          return "alert alert-error";
        } else if ((1 <= daysLeft && daysLeft < 7)) {
          return "alert";
        } else {
          return "alert alert-info";
        }
      }
    }, data));
  });
};

exports.accountPost = function(req, res) {
  debugger;
  var errorHandler, json, steps, user;

  json = req.body;
  user = req.user.getUser();
  steps = [
    function(step) {
      if (json.timezone === user.timezone_id) {
        exports.account(req, res);
      }
      check(json.timezone, 'Timezone is invalid!').isInt();
      step.data.timezone = sanitize(json.timezone).toInt();
      return step.next();
    }, function(step) {
      user.timezone_id = step.data.timezone;
      return model.saveUser(user, function(res, err) {
        step.data.saveErr = err;
        return step.next();
      });
    }, function(step) {
      if (step.data.saveErr != null) {
        common.logger.error("Error saving user's timezone", err);
        throw {
          message: "There was a server error!"
        };
      }
      return step.next();
    }, function(step) {
      exports.account(req, res);
      return step.next();
    }
  ];
  errorHandler = function(error) {
    json.errorMsg = (error != null ? error.message : void 0) != null ? error.message : error.toString();
    common.logger.error(json.errorMsg);
    return exports.account(req, res, json);
  };
  return ctrl(steps, {
    errorHandler: errorHandler
  }, function() {
    return {};
  });
};
