// Generated by CoffeeScript 1.6.2
var common, ctrl, model, sanitize;

common = require('../common');

ctrl = require('ctrl');

model = require('../database/model');

sanitize = require('validator').sanitize;

exports.login = function(req, res, data) {
  return res.render('home.ect', common.extend({
    page: 'Login',
    req: req
  }, data));
};

exports.loginPost = function(req, res) {
  var afterSuccessfulLogin, errorHandler, json, steps;

  json = req.body;
  console.log(json != null ? json.email : void 0);
  steps = [
    function(step) {
      common.logger.debug("Parse the json for login");
      if ((json.email == null) || json.email === "") {
        throw "Please include an email address";
      }
      if ((json.password == null) || json.password === "") {
        throw "Please include a password";
      }
      return step.next();
    }, function(step) {
      common.logger.debug("Get the user");
      return model.getUserForEmail(json.email, step.next);
    }, function(step, user, err) {
      common.logger.debug("Make sure the database call to look up the user had no problems");
      if (err != null) {
        common.logger.error(err);
        throw "There was a server error";
      }
      step.data.user = user;
      return step.next();
    }, function(step) {
      common.logger.debug("Check user login");
      if (step.data.user == null) {
        common.logger.info("Invalid user");
        throw "Invalid username or password.";
      }
      if (step.data.user.email !== json.email) {
        common.logger.error("Returned user had the wrong email");
        throw "There was an error on the server.";
      }
      return step.next();
    }, function(step) {
      common.logger.debug("Verify the password against the DB hash");
      if (!require('password-hash').verify(sanitize(json.password.toLowerCase()).trim(), step.data.user.password)) {
        common.logger.info("Invalid password");
        throw "Invalid username or password.";
      }
      return step.next();
    }, function(step) {
      common.logger.debug("Log the user in after success");
      req.user.login(step.data.user);
      return step.next();
    }
  ];
  errorHandler = function(step, error) {
    json.errorMsg = (error != null ? error.message : void 0) != null ? error != null ? error.message : void 0 : error.toString();
    common.logger.error(json.errorMsg);
    delete json.password;
    return exports.login(req, res, json);
  };
  afterSuccessfulLogin = function() {
    return res.redirect('/account.html');
  };
  return ctrl(steps, {
    errorHandler: errorHandler
  }, afterSuccessfulLogin);
};

exports.ensureLogin = function(req, res, next) {
  if (req.user.loggedIn()) {
    return next();
  } else {
    return res.redirect('/login.html');
  }
};

exports.logout = function(req, res) {
  req.user.logout();
  return res.redirect('/login.html');
};
